name = "banky-server"
main = "src/worker.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
workers_dev = true

[vars]
APP_ID = "YOUR_ENABLE_BANKING_APP_ID"
ENABLE_BANKING_REDIRECT_URL = "http://localhost:5173/auth/callback"
FRONTEND_URL = "http://localhost:5173"
ENABLE_BANKING_BASE_URL = "https://api.enablebanking.com"

[[d1_databases]]
binding = "DB"
database_name = "banky-db"
database_id = "786e564e-f05f-4af4-a9ce-e7ab3767658b"

